---
language: ruby
bundler_args: --full-index
before_install: rm Gemfile.lock || true
script: ["bundle exec rake test"]
rvm:
  - 2.4
env:
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.4.0" STRICT_VARIABLES=yes
#matrix:
#  include:
#    - rvm: default
#      sudo: required
#      dist: trusty
#      services: docker
#      env: BEAKER_set="ubuntu-16.04" PUPPET_INSTALL_VERSION="5.4.0"
#      bundler_args:
#      script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
#    - rvm: default
#      sudo: required
#      dist: trusty
#      services: docker
#      env: BEAKER_set="debian-7" PUPPET_INSTALL_VERSION="5.4.0"
#      bundler_args:
#      script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
#    - rvm: default
#      sudo: required
#      dist: trusty
#      services: docker
#      env: BEAKER_set="centos-7" PUPPET_INSTALL_VERSION="5.4.0"
#      bundler_args:
#      script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
#    - rvm: default
#      sudo: required
#      dist: trusty
#      services: docker
#      env: BEAKER_set="oraclelinux-7" PUPPET_INSTALL_VERSION="5.4.0"
#      bundler_args:
#      script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
deploy:
  provider: puppetforge
  user: kschu91
  password:
    secure: IugZvi1dVsssaPsvrj0AeLeDfMXsAHgROi8Arppn0ndIQbYzQfTN/7xzrTV4O+9yc8RZVsWwObjsais7ciPhbnBT9w90zep0fhGEwN16WtfoSU3y8sbe7E2i6vrBix5ffitv00S1I/DIZ+u6+kUjjLuPo0H/IMjjBUQav9IYQEjQ7/Z33I7fyjL1xTsSXdRC10v//YzCXzjfbUX9M10Oa0kEYD/Cv4/SvEj4X9jlh8LdKPXqQsgxpzd7BuRSneWZc28y45tHU5zeQxsU21kM+xoVSQ063eJgY+61Y8R+KUrn5G+lTT/urtwdCDliCI0KOyO3GsbZ6bNGRDuw08tiZUjPeMVggUI/tkOFiPQma6TtsU2Wz4QS4gOGd3C/Molz9FKVPFyiNTr0lF1FwuK3MtJwmIUNomi3b9ZKP3CSjyf308C4etvSoEOQwyyDzt0dTRH9i2V71COhb1BP40bsqjMx3tpbbsoOcyFOo27IkwsSC1/6HqgKRF+YAgqONvuSsHxUPuOxNsmK338/pFqwXIBc7u3RmA4IN/NE3v4ueleVoemGAUeY5kFdWdMh2jGzpjgvxIAwj8aXDsKRHb5LLpTQQGlaqyp83Bbbi9ZvtuXjlWqeEgmLpMVV2eirQn/fnppC6EOGHsQXHBmfNu/gZ4Kzgvp7zcmUunjYVY5MEjs=
  on:
    tags: true
    # Only publish if our main Ruby target builds
    rvm: 2.4
    condition: $PUPPET_GEM_VERSION = "~> 5.4.0"
